version: "{build}"

branches:
  only:
    - master

clone_folder: c:\tusk

environment:
  GOPATH: c:\gopath

stack: go 1.12

init:
  # Add GOPATH to reference installed binary
  - set PATH=%GOPATH%\bin;%PATH%
  # Add MinGW for gcc
  - set PATH=C:\msys64\mingw64\bin;%PATH%

build_script:
  - go install

test_script:
  - tusk --quiet test --verbose
